### ISSUE TITLE
[Question] C# byte[] <---> GO []byte (return to C# and input to GO)

### ISSUE THREAD

**Issue by aleqsss** [vladimirvivien/go-cshared-examples#27]
@Digital-512 I'd once again like to thank you for your thorough answer on my other question #26. Not only did you provide excellent examples, but you also complemented them with explanations so that I actually managed to learn something at the same time.

Now I wonder if I'd be too bold, to once again ask for your input.

I managed to use the examples in this repository, to provide `int` inputs from C# to the exported Go [Add()](https://github.com/vladimirvivien/go-cshared-examples/blob/ba0c7d9719b26c6d47cc830c76cd8fdbdbd74221/awesome.go#L16) function, and then return an `int` from that exported Go function to the C# code.

However, I need to be able to input a C# `byte[]` to an exported GO function expecting a `[]byte` input. I also need to return a `[]byte` from that exported Go function to a C# `byte[]`.

Consider the below examples.
 
Go exported function (pseduo):
```Go
//export ReturnBytes
func InputAndReturnBytes(byteSlice []byte) []byte {
	// Process the byteSlice []byte input
	// return processedByteSlice
}
```
From C#, how would I input a `byte[]` to the byteSlice `[]byte` argument? How would I assign the returned `[]byte`/GoSlice to a `byte[]` in C#?

Looking at the generated header file for such an exported function:
`extern __declspec(dllexport) GoSlice InputAndReturnBytes(GoSlice byteSlice);`

One can see that it expects a GoSlice for the byteSlice input parameter, and returns a GoSlice. 

I've tried in various ways, e.g.:
* To input a C# `byte[]` using the GoSlice struct which is defined earlier (also in the examples of this repository).
* Assign the returned GoSlice from the exported Go function to the C# GoSlice struct.

But unfortunately both to no avail.

I struggle on how to work with the byte array/slice between the two languages/interfaces.

I can see that in Go:
```Go
// byte is an alias for uint8 and is equivalent to uint8 in all ways. It is
// used, by convention, to distinguish byte values from 8-bit unsigned
// integer values.
type byte = uint8
```
And in the CGO generated header file, that `typedef unsigned char GoUint8;` is actually defined.

Perhaps I need to create a GoByte/GoUint8 struct of sorts in C#, and then put it in the GoSlice? I actually have no idea.

As you can see, I have no idea what I'm doing here. 🙄
Crossing my fingers you'll have some time over to shed some light. 🤞

**Comment by Digital-512** [comment]
Hi @aleqsss, To pass a C# byte array to a Go []byte slice, you can use the same GoSlice struct as before:
```cs
public struct GoSlice
{
    public IntPtr data;
    public long len, cap;
    public GoSlice(IntPtr data, long len, long cap)
    {
        this.data = data;
        this.len = len;
        this.cap = cap;
    }
}
```
C# P/Invoke Signature:
```cs
[DllImport(libName, CallingConvention = CallingConvention.Cdecl)]
public static extern GoSlice InputAndReturnBytes(GoSlice byteSlice);
```
Here's an example of how you can call the InputAndReturnBytes function:
```cs
// Generate some bytes in C#
byte[] data = Encoding.UTF8.GetBytes("Hello, world!");

IntPtr data_ptr = Marshal.AllocHGlobal(data.Length);
Marshal.Copy(data, 0, data_ptr, data.Length);

var bytes = new GoSlice(data_ptr, data.Length, data.Length);
GoSlice returnedSlice = InputAndReturnBytes(bytes);
byte[] resultData = new byte[returnedSlice.len];
Marshal.Copy(returnedSlice.data, resultData, 0, resultData.Length);

// Free the unmanaged memory
Marshal.FreeHGlobal(data_ptr);

// Print returned data
string resultString = Encoding.UTF8.GetString(resultData);
Console.WriteLine(resultString);
```
In the above code, we create a sample byte array data using the `Encoding.UTF8.GetBytes()` method to encode the string "Hello, world!" in UTF-8 format. The GoSlice struct is then passed as an argument to the `InputAndReturnBytes()` function. The `InputAndReturnBytes()` function performs some operation on the input byte array and returns the modified byte array as another GoSlice. The `Marshal.Copy()` method is used again to copy the contents of the returned GoSlice to a new managed byte array resultData. Finally, we free the unmanaged memory and the modified byte array is converted back to a string using the `Encoding.UTF8.GetString()` method and printed to the console.

The passing of the byte array to the Go function is very similar to the example shown with []int in this repository. However, the difference occurs when we want to pass a slice from Go back to C#. I show an example:
```go
//export InputAndReturnBytes
func InputAndReturnBytes(byteSlice []byte) []byte {
    // Convert bytes from C# to string
    str := string(byteSlice)
    fmt.Println(str) // "Hello, world!"

    // create a new byte slice containing some data
    data := []byte("Hello from Go!")
    size := len(data)

    // allocate a C buffer to hold the data
    buffer := C.CBytes(data)

    // return the C buffer as a byte array
    return (*[1 << 30]byte)(buffer)[:size:size]
}
```
In the above code, an unmanaged memory buffer is allocated using the `C.CBytes()` function, which is used to allocate a C buffer that can be accessed from Go. The data byte slice is copied into this buffer. Finally, a new byte slice is created using the `(*[1 << 30]byte)(buffer)[:size:size]`. This creates a new byte slice with a length of size and a capacity of size, using the memory buffer as its underlying storage. The resulting byte slice is returned as the output of the function.

In this case, the buffer variable is allocated using the C.CBytes() function, which internally uses C.malloc() to allocate memory. Therefore, you should use C.free() to free the buffer variable after you have used the function as follows:
```go
// #include <stdlib.h>
C.free(buffer)
```
If you just tried to return []byte normally (see the code below), it wouldn't work because functions in cgo cannot directly return slice/map data types with a go pointer (you can read more about this [here](https://www.sobyte.net/post/2022-05/go-java/)). You would get an error `panic: runtime error: cgo result has Go pointer`.
```go
//export InputAndReturnBytes
func InputAndReturnBytes(byteSlice []byte) []byte {
    // Convert bytes from C# to string
    str := string(byteSlice)
    fmt.Println(str) // "Hello, world!"

    // create a new byte slice containing some data
    data := []byte("Hello from Go!")
    return data
}
```
Now, if you have the exported function `InputAndReturnBytes()` in Go code, the result after executing command `dotnet run` should be like this:
```
> dotnet run
Hello, world!
Hello from Go!
```

**Comment by aleqsss** [comment]
Thank you once again for taking the time create such a good answer to my questions, with excellent examples and explanations. I can do nothing more but thank you! I've tried all of the examples, which works exactly as promised.

However, I'm trying to create two extension methods, to be able to reuse the code:

**This one works as I'd expect.**
ToByteArray() (which, as per your example, takes the `InputAndReturnBytes()` returned byte GoSlice and converts to a C# byte array):
```C#
internal static byte[] ToByteArray(this GoSlice goSlice)
{
    byte[] resultData = new byte[goSlice.len];
    Marshal.Copy(goSlice.data, resultData, 0, resultData.Length);

    return resultData;
}
```
**This one doesn't works as I'd expect.**
ToGoSlice():
```C#
internal static GoSlice ToGoSlice(this byte[] byteArray)
{
    IntPtr data_ptr = Marshal.AllocHGlobal(byteArray.Length);
    Marshal.Copy(byteArray, 0, data_ptr, byteArray.Length);

    GoSlice bytes = new GoSlice(data_ptr, byteArray.Length, byteArray.Length);

    Marshal.FreeHGlobal(data_ptr);

    return bytes;
}
```
Which I then call like so:
```C#
byte[] data = Encoding.UTF8.GetBytes("Hello, world!");
GoSlice bytes = data.ToGoSlice();
byte[] resultData = InputAndReturnBytes(bytes).ToByteArray();
```
However, the extension method **ToGoSlice()** works if I remove the `Marshal.FreeHGlobal(data_ptr);` method. I'm not sure if I'm on the wrong path here, but is there some way I could "copy" the data of  `GoSlice bytes = new GoSlice(data_ptr, byteArray.Length, byteArray.Length);` to managed memory before returning it as a GoSlice, so that I can free the **data_ptr** in my extension method? Or is there a better way to go at this?

Best regards

**Comment by Digital-512** [comment]
@aleqsss The reason why your current implementation of the ToGoSlice() extension method fails when you call Marshal.FreeHGlobal(data_ptr) is that the GoSlice struct you're returning still references the memory block allocated with Marshal.AllocHGlobal(). So when you free the memory block, the GoSlice struct becomes invalid and may cause unexpected behavior or crashes.

One way to avoid this problem is to create a new GoSlice struct that refers to a copy of the data in managed memory, instead of the unmanaged memory block. You can use the Marshal.Copy() method to copy the data from the unmanaged memory block to a new managed byte array, and then create a new GoSlice struct that refers to that array.

Here's an updated implementation of the ToGoSlice() extension method that copies the data to managed memory before creating the GoSlice struct:
```cs
internal static GoSlice ToGoSlice(this byte[] byteArray)
{
    IntPtr data_ptr = Marshal.AllocHGlobal(byteArray.Length);
    Marshal.Copy(byteArray, 0, data_ptr, byteArray.Length);

    // Create a managed byte[] array and copy the data from the unmanaged memory to it
    byte[] data = new byte[byteArray.Length];
    Marshal.Copy(data_ptr, data, 0, byteArray.Length);

    // Create a new GoSlice struct using the managed byte[] array
    GoSlice bytes = new GoSlice(Marshal.UnsafeAddrOfPinnedArrayElement(data, 0), byteArray.Length, byteArray.Length);

    // Free the unmanaged memory
    Marshal.FreeHGlobal(data_ptr);

    return bytes;
}
```
In this implementation, we first allocate the unmanaged memory using Marshal.AllocHGlobal() as before. We then create a new managed byte[] array and copy the data from the unmanaged memory to it using Marshal.Copy(). Next, we create a new GoSlice struct and set its data field to the address of the first element of the managed byte[] array using Marshal.UnsafeAddrOfPinnedArrayElement(). Finally, we free the unmanaged memory using Marshal.FreeHGlobal().

With this implementation, you can safely call Marshal.FreeHGlobal(data_ptr) in the extension method without affecting the validity of the GoSlice struct returned.

**Comment by aleqsss** [comment]
That's what I thought and tried, but I had no idea how to implement it. I don't know how to thank you enough!

Do you by any chance have a "buy me a coffee" donation link or something like that? I'm working on a project at work and you have no idea how much you've saved me, so I'd like to express my gratitude in some way. I can assure you that I don't take your help for granted.

**Comment by Digital-512** [comment]
@aleqsss Good luck with your project! I don't have a special "buy me a coffee" link, but you can donate to this PayPal: totalpun@mail.com or via [this link](https://www.vpsnet.com/en/add-funds/?id=643fb86c8172fb56d8898497eb682c27&id2=e02a47ab2887a5b1bd9f08b99a7c446a).

**Comment by aleqsss** [comment]
Sent you a little something to [totalpun@mail.com](mailto:totalpun@mail.com) as a token of my appreciation.

**Comment by aleqsss** [comment]
Thinking about the below part of your answer:

_In this case, the buffer variable is allocated using the C.CBytes() function, which internally uses C.malloc() to allocate memory. Therefore, you should use C.free() to free the buffer variable after you have used the function as follows:_

```Go
// #include <stdlib.h>
C.free(buffer)
```
Since I'm running the exported functions via **C# P/Invoke**, how would I come at calling the `C.free(buffer)` command from the Go code, after I've used the function?

**Comment by Digital-512** [comment]
@aleqsss You can try to create another exported function to call `C.free(buffer)`. It depends on your implementation how you might do this.

Here is one way how you can do it. First, you need to modify the `InputAndReturnBytes()` function to return the buffer directly:
```go
//export InputAndReturnBytes
func InputAndReturnBytes(byteSlice []byte) (unsafe.Pointer, int, int) {
    // Convert bytes from C# to string
    str := string(byteSlice)
    fmt.Println(str) // "Hello, world!"

    // create a new byte slice containing some data
    data := []byte("Hello from Go!")
    size := len(data)

    // allocate a C buffer to hold the data
    buffer := C.CBytes(data)

    // return the C buffer, its size and capacity
    return buffer, size, size
}
```
Then create a new exported Go function `FreeGoBuffer()`:
```go
//export FreeGoBuffer
func FreeGoBuffer(buffer unsafe.Pointer) {
    C.free(buffer)
}
```
Don't forget to use the `stdlib.h` and `unsafe` imports in Go code, as shown below. The `#include stdlib.h` is used here for the `C.free()` function.
```go
// #include <stdlib.h>
import "C"
import "unsafe"
```
C# P/Invoke Signature:
```cs
[DllImport(libName, CallingConvention = CallingConvention.Cdecl)]
public static extern void FreeGoBuffer(IntPtr goBuffer);
```
Now modify `ToBufferArray()` extension function to call `FreeGoBuffer()` after copying the buffer data to managed memory:
```cs
internal static byte[] ToByteArray(this GoSlice goSlice)
{
    byte[] resultData = new byte[goSlice.len];
    Marshal.Copy(goSlice.data, resultData, 0, resultData.Length);

    // Free the buffer
    Awesome.FreeGoBuffer(goSlice.data);

    return resultData;
}
```
Note: replace `Awesome` with the name of the class where the C# P/Invoke Signature is specified.

This should work in the normal case. If something doesn't work, please let me know.

**Comment by aleqsss** [comment]
Awesome, thank you! 👍

As soon as I have the time, I'll try this out. Will report back here with the results.

**Comment by aleqsss** [comment]
As far as I can see, this FreeGoBuffer implementation seems to be working (I don't get any obvious errors at least). So big thank you for that! 🙂

However, I got another issue (which was present even before this free go buffer stuff). So I've exported another function to replicate/demonstrate:
```Go
//export TestMultipleInput
func TestMultipleInput(string1 string, slice1 []string, string2 string, slice2 []string) {
	fmt.Println(string1)
	fmt.Printf("Strings slice 1: %v", slice1)
	fmt.Println(string2)
	fmt.Printf("Strings slice 2: %v", slice2)
}
```
C# P/Invoke Signature:
```C#
[DllImport("shared.dll", CallingConvention = CallingConvention.Cdecl)]
internal static extern void TestMultipleInput(GoString string1, GoSlice slice1, GoString string2, GoSlice slice2);
```

The first time I ran the function I got the following output:
```
Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]
```

The second time:
```
Input1
Strings slice 1: [String_array_2_Block_1 String_array_2_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]
```

As you can see, the second time both `slice1` and `slice2` contained the same value of `[String_array_2_Block_1 String_array_2_Block_2]`.

If I ran it multiple consecutive times the output varied, but seemed to be mixing the slices/string arrays:
```
Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2] 

Input1
Strings slice 1: [String_array_2_Block_1 String_array_2_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]     

Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]

Input1
Strings slice 1: [String_array_2_Block_1 String_array_2_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]

Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]

Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]

Input1
Strings slice 1: [String_array_1_Block_1 String_array_1_Block_2]Input2
Strings slice 2: [String_array_2_Block_1 String_array_2_Block_2]

and so on...
```

So sometimes (seemingly randomly) I get what I except and sometimes the slices seems to be mixed. What do you think I'm doing wrong here?

Best regards

**Comment by Digital-512** [comment]
@aleqsss Try to add `[StructLayout(LayoutKind.Sequential)]` attribute above GoSlice and GoString structs. However, I could not reproduce the problem you have. To me, this does not occur. Can you show me the main code how you create and use GoString and GoSlice and how you call the function `TestMultipleInput()` in C#?

**Comment by aleqsss** [comment]
Of course! 🙂

(I already use `[StructLayout(LayoutKind.Sequential)]` as per your previous recommendations).

GoString:
```C#
[StructLayout(LayoutKind.Sequential)]
internal struct GoString
{
    internal IntPtr data;
    internal long len;

    internal GoString(string str)
    {
        data = Marshal.StringToHGlobalAnsi(str);
        len = str.Length;
    }

    public static implicit operator GoString(string str) => new GoString(str);
}
```

GoSlice:
```C#
[StructLayout(LayoutKind.Sequential)]
internal struct GoSlice
{
    internal IntPtr data;
    internal long len, cap;
    internal GoSlice(IntPtr data, long len, long cap)
    {
        this.data = data;
        this.len = len;
        this.cap = cap;
    }
}
```

TestMultipleInput() function call:
```C#
GoString string1 = new GoString("Input1");
GoString string2 = new GoString("Input2");

GoSlice stringArray1 = new string[] { "String_array_1_Block_1", "String_array_1_Block_2" }.ToGoSlice();
GoSlice stringArray2 = new string[] { "String_array_2_Block_1", "String_array_2_Block_2" }.ToGoSlice();

TestMultipleInput(string1, stringArray1, string2, stringArray2);
```

C# P/Invoke Signature:
```C#
[DllImport("shared.dll", CallingConvention = CallingConvention.Cdecl)]
internal static extern void TestMultipleInput(GoString string1, GoSlice slice1, GoString string2, GoSlice slice2);
```

Extension methods:

ToGoSlice() (string[]):
```C#
internal static GoSlice ToGoSlice(this string[] strArray)
{
    IntPtr stringsPtr = IntPtr.Zero;

    try
    {
        GoString[] goStrings = new GoString[strArray.Length];
        for (int i = 0; i < strArray.Length; i++)
        {
            goStrings[i] = new GoString(strArray[i]);
        }
        stringsPtr = Marshal.AllocHGlobal(Marshal.SizeOf<GoString>() * goStrings.Length);
        for (int i = 0; i < goStrings.Length; i++)
        {
            Marshal.StructureToPtr(goStrings[i], stringsPtr + i * Marshal.SizeOf<GoString>(), false);
        }
        GoSlice goSlice = new GoSlice(stringsPtr, goStrings.Length, goStrings.Length);

        return goSlice;
    }
    finally
    {
        Marshal.FreeHGlobal(stringsPtr);
    }
}
```
ToGoSlice() (byte[]):
```C#
internal static GoSlice ToGoSlice(this byte[] byteArray)
{
    IntPtr data_ptr = IntPtr.Zero;

    try
    {
        data_ptr = Marshal.AllocHGlobal(byteArray.Length);
        Marshal.Copy(byteArray, 0, data_ptr, byteArray.Length);

        byte[] data = new byte[byteArray.Length];
        Marshal.Copy(data_ptr, data, 0, byteArray.Length);

        GoSlice bytes = new GoSlice(Marshal.UnsafeAddrOfPinnedArrayElement(data, 0), byteArray.Length, byteArray.Length);

        return bytes;
    }
    finally
    {
        Marshal.FreeHGlobal(data_ptr);
    }
}
```
ToByteArray() (GoSlice):
```C#
internal static byte[] ToByteArray(this GoSlice goSlice)
{
    byte[] resultData = new byte[goSlice.len];
    Marshal.Copy(goSlice.data, resultData, 0, resultData.Length);

    FreeGoBuffer(goSlice.data);

    return resultData;
}
```

**Comment by Digital-512** [comment]
@aleqsss The problem is in the `ToGoSlice() (string[])` method, because you first return a GoSlice structure that points to an unmanaged memory block allocated using `Marshal.AllocHGlobal()`, and then you free it using `Marshal.FreeHGlobal(stringsPtr)`. So when you free the memory block, the GoSlice struct becomes invalid and may cause unexpected behavior. You should do exactly the same as in the `ToGoSlice()(byte[])` method. Make a copy of the data in managed memory before returning the GoSlice structure.

Here's an updated implementation of the ToGoSlice() extension method that copies the data to managed memory before creating the GoSlice struct:
```cs
internal static GoSlice ToGoSlice(this string[] strArray)
{
    IntPtr stringsPtr = IntPtr.Zero;

    try
    {
        GoString[] goStrings = new GoString[strArray.Length];
        int stringsSize = Marshal.SizeOf<GoString>() * goStrings.Length;

        for (int i = 0; i < strArray.Length; i++)
        {
            goStrings[i] = new GoString(strArray[i]);
        }
        stringsPtr = Marshal.AllocHGlobal(stringsSize);
        for (int i = 0; i < goStrings.Length; i++)
        {
            Marshal.StructureToPtr(goStrings[i], stringsPtr + i * Marshal.SizeOf<GoString>(), false);
        }

        // Create a managed byte[] array and copy the data from the unmanaged memory to it
        byte[] data = new byte[stringsSize];
        Marshal.Copy(stringsPtr, data, 0, stringsSize);

        // Create a new GoSlice struct using the managed byte[] array
        GoSlice goSlice = new GoSlice(Marshal.UnsafeAddrOfPinnedArrayElement(data, 0), goStrings.Length, goStrings.Length);

        return goSlice;
    }
    finally
    {
        Marshal.FreeHGlobal(stringsPtr);
    }
}
```
With this implementation, you can safely call Marshal.FreeHGlobal(stringsPtr) in the extension method without affecting the validity of the GoSlice struct returned.

**Comment by aleqsss** [comment]
You're awesome, thanks a bunch!

While on the the thread, is it possible to pass a struct/object from C# to Go, to continue the code I already have? If yes, I could create a new issue in this repo, where I explain a bit further what I need.

**Comment by Digital-512** [comment]
@aleqsss Yes, it is possible to pass a struct or object from C# to Go.
